name: Download artifact from another repo and publish
on:
  workflow_dispatch:
    inputs:
      download_branch:
        description: The branch to download the artifacts from
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.DOWNLOAD_ARTIFACT}}
        workflow: __docs-generate-sphinx.yml
        branch: '${{ github.event.inputs.download_branch }}'
        repo: github/semmle-code
        path: site/test/ 
    - name: Check download 
      working-directory: '${{ github.workspace }}'
      run: ls -la
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
