name: Download artifact from another repo and publish
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.DOWNLOAD_ARTIFACT}}
        workflow: __docs-generate-sphinx.yml
        branch: main
        repo: github/semmle-code
    - name: Check download 
      working-directory: '${{ github.workspace }}'
      run: ls -la	   
