name: Publish QLDoc
on:
  workflow_dispatch:
    inputs:
      download_branch:
        description: The branch to download the artifacts from
        required: true
      destination:
        description: The path to add the artifact to

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Delete existing docs folder
      run: |
        rm -r '${{ github.event.inputs.destination }}'/codeql-libraries/**;
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.DOWNLOAD_ARTIFACT}}
        workflow: __docs-generate-qldoc.yml
        branch: '${{ github.event.inputs.download_branch }}'
        repo: github/semmle-code 
    - name: Move artifacts 
      run: mv artifact/** '${{ github.event.inputs.destination }}'/codeql-libraries && rm -r artifact &&
    - name: Unzip artifacts
      working-directory: ${{ github.event.inputs.destination }}'/codeql-libraries
      run: |    
        ls -la;
        unzip pack-cpp-qloc.zip -d cpp;
        unzip pack-csharp-qloc.zip -d csharp;
        unzip pack-go-qloc.zip -d go;
        unzip pack-java-qloc.zip -d java;
        unzip pack-javascript-qloc.zip -d javascript;
        unzip pack-python-qloc.zip -d python;
        rm -r pack-ql-qldoc.zip
    - name: Check files 
      working-directory: ${{ github.event.inputs.destination }}'/codeql-libraries
      run: ls -la
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: update codeql documentation
        title: '[CodeQL standard libraries] Automated PR to update the CodeQL standard libraries (${{ github.event.inputs.download_branch }})'
        body: |
          PR generated by actions to update the CodeQL standard libraries docs.
          Updating from the '${{ github.event.inputs.download_branch }}' branch.
        branch: codeql-libraries-update/${{ github.event.inputs.download_branch }}
        delete-branch: true
