name: Publish QLDoc
on:
  workflow_dispatch:
    inputs:
      download_branch:
        description: The branch to download the artifacts from
        required: true
      destination:
        description: The path to add the artifact to

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Delete existing docs folder
      run: |
        rm -r '${{ github.event.inputs.destination }}'/codeql-libraries/**;
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.DOWNLOAD_ARTIFACT}}
        workflow: __docs-generate-qldoc.yml
        branch: '${{ github.event.inputs.download_branch }}'
        repo: github/semmle-code 
    - name: Check download
      run: cd artifact && ls -la
    - name: Move and rename artifacts 
      run: |
        mv artifact/** '${{ github.event.inputs.destination }}'/codeql-libraries && rm -r artifact;
        cd '${{ github.event.inputs.destination }}'/codeql-libraries;
        mv pack-cpp-qldoc.zip cpp;
        mv pack-csharp-qldoc.zip csharp;
        mv pack-go-qldoc.zip go;
        mv pack-java-qldoc.zip java;
        mv pack-javascript-qldoc.zip javascript;
        mv pack-python-qldoc.zip python;
        rm -r pack-ql-qldoc.zip
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: update codeql documentation
        title: '[CodeQL standard libraries] Automated PR to update the CodeQL standard libraries (${{ github.event.inputs.download_branch }})'
        body: |
          PR generated by actions to update the CodeQL standard libraries docs.
          Updating from the '${{ github.event.inputs.download_branch }}' branch.
        branch: codeql-libraries-update/${{ github.event.inputs.download_branch }}
        delete-branch: true
